spring.application.name=osm-to-kuwaiba

spring.datasource.url=jdbc:postgresql://localhost:5432/osm
spring.datasource.username=osmuser
spring.datasource.password=osmpass

# These settings help you understand and debug the SQL operations that JPA performs behind the scenes.
# Enables logging of the generated SQL queries from JPA/Hibernate to the console.
spring.jpa.show-sql=true  

# Formats the logged SQL queries, making them more readable.
spring.jpa.properties.hibernate.format_sql=true  

#hibernate.dialect org.hibernate.spatial.dialect.postgis.PostgisDialect
# depreciated because standard in hibernate 6+ (using hibernete 7)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# see https://stackoverflow.com/questions/42135114/how-does-spring-jpa-hibernate-ddl-auto-property-exactly-work-in-spring
# this will update your existing database schema but not change existing tables, columns, or constraints. It will only add new tables, columns, or constraints as needed to match the current entity mappings in your application. It will not drop any existing tables or columns, and it will not modify any existing constraints. This is a safe option for development and testing environments where you want to keep your existing data intact while allowing Hibernate to manage the schema changes.
spring.jpa.hibernate.ddl-auto=update

# Adding uprn csv path (This is only for when the spring boot application is not containerised,
# when it is eventually containerised then the path to the data is specified in docker yaml.)
uprn.csv.path=../container-fs/data/uprns.csv
