services:
  db:
    image: pgrouting/pgrouting:15-3.3-3.4.1
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=osmuser
      - POSTGRES_PASSWORD=osmpass
      - POSTGRES_DB=osm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./container-fs/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U osmuser -d osm" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 60s

  importer:
    image: iboates/osm2pgsql:2.2.0
    container_name: importer
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./container-fs/data:/data
    environment:
      - PGHOST=db
      - PGUSER=osmuser
      - PGPASSWORD=osmpass
      - PGDATABASE=osm
    entrypoint: /bin/sh -c
    command: >
      "echo 'Starting osm2pgsql import...';
       FILE=$$(ls /data/*.xml /data/*.osm.pbf /data/*.osm /data/*.pbf 2>/dev/null | head -1);
       echo \"Importing $$FILE\";
       osm2pgsql --create --slim --hstore $$FILE"

  pgadmin:
    image: dpage/pgadmin4:9.13.0
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: minad1234
      PGADMIN_SERVER_JSON_FILE: /pgadmin/servers.json
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./container-fs/pgadmin/:/pgadmin

  app:
    build:
      context: ./osm-to-kuwaiba-spring-boot
      dockerfile: Dockerfile
    container_name: app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      importer:
        condition: service_completed_successfully
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/osm
      SPRING_DATASOURCE_USERNAME: osmuser
      SPRING_DATASOURCE_PASSWORD: osmpass
        # Overiding csv path
      UPRN_CSV_PATH: /data/uprns.csv
    volumes:
      - ./container-fs/data:/data

  kuwaiba:
    #    image: ${DOCKER_REGISTRY:-docker.io}/neotropic/kuwaiba:${KUWAIBA_VERSION:-v2.1-nightly}
    image: onms-integration/kuwaiba
    build: ./container-fs/kuwaiba/
    container_name: kuwaiba
    hostname: kuwaiba
    #   environment:
    #    URL_DATA: https://sourceforge.net/projects/kuwaiba/files/Version%202.x/kuwaiba_server_2.1.1_stable.zip
    volumes:
      - data-kuwaiba:/data
      - ./container-fs/kuwaiba/start.sh:/start.sh
      - ./container-fs/kuwaiba/data-overlay:/data-overlay
      - ./container-fs/kuwaiba/data-zip:/data-zip
    ports:
      - "8085:8080"
      - "8086:8081"

      # To combine stderr and stdout into the stdout stream, we append this to a command: 2>&1
      # command: sh -c "java -jar /opt/programs/kuwaiba_server_2.1.1-stable.jar > /data/logs/kuwaiba_$(date +%Y%m%d_%H%M%S).log 2>&1"
    command: sh /start.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:8080/kuwaiba/"]
      interval: 30s
      timeout: 5s
      retries: 1
    #networks:
    #       kuwaiba-net:

             
volumes:
  postgres_data:
  pgadmin_data:
  data-kuwaiba: {}